### ISSUE TITLE
Update style due to small screens issue

### ISSUE THREAD

**Issue by Andrei-Straut** [Andrei-Straut/psga#2]
On small screens, there is a horizontal scrollbar due 'page-inner' fixed margin-left (current 60px). Replace fixed margin values with auto and add a fixed padding-left. Also, this way the element width can be increased to 100% (current 95). Style should be the following:

```css
#page-inner {
  width: 100%;
  margin: auto;
  background-color: #fff !important;
  padding: 10px;
  padding-left: 60px;
}
```
